name: Daily Selenium Test

on:
  schedule:
    # Runs at 7 AM UTC every day (convert to your local time if needed)
    - cron: '0 7 * * *'

jobs:
  run-selenium-script:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      # Run the Selenium script
      - name: Run Selenium script
        run: python test.py
